# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formexample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='collage_city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
