# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formexample', '0002_collage_collage_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collage',
            table='collage',
        ),
    ]
